name: test-hello-world
# Identitfy the event that the workflow runs when trigers
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  #name
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello-world-echo
        run: echo "Hello World"
        shell: bash
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye-world
      - run: echo "Bye world"
      - shell: bash
