name: issue triger

on:
  issues:
    types: [opened]
jobs:
  issue-comment: 
    runs-on: ubuntu-latest
    steps:
      - name: issue-comment-with-API
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      - run: |
            gh api -X POST \
            http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='hello from api'
          
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ORGANIZATION: ${{ github.event.organization.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
